version: 2.1
workflows:
  pipeline:
    jobs:
      - terraform-apply:
          filters:
            branches:
              only:
                /(circleci)/
                # /(dev)|(stg)|(prd)/
jobs:
  terraform-apply:
    machine: true
    environment:
      ### --------------------------------------------------
      ### Find and Replace
      TF_VAR_app_name: tfmultienv
      TF_VAR_region: &AWS_REGION eu-west-1
      ### --------------------------------------------------
      AWS_REGION: *AWS_REGION
      AWS_DEFAULT_REGION: *AWS_REGION
      TERRAFORM_VERSION: 0.13.1
      LIVE_DIR: live
      BACKEND_TPL: backend.tf.tpl

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y git
      - run:
          name: prepare-files-folders
          command: |
            ./scripts/prepare-files-folders.sh
      - run:
          name: prepare-backend
          command: |
            declare -n AWS_ACCESS_KEY_ID_SECRET_NAME=aws_access_key_id_${CIRCLE_BRANCH}
            declare -n AWS_SECRET_ACCESS_KEY_SECRET_NAME=aws_secret_access_key_${CIRCLE_BRANCH}
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_SECRET_NAME}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_SECRET_NAME}          
            ./scripts/prepare-backend.sh
      - run:
          name: terraform-apply
          command: |
            declare -n AWS_ACCESS_KEY_ID_SECRET_NAME=aws_access_key_id_${CIRCLE_BRANCH}
            declare -n AWS_SECRET_ACCESS_KEY_SECRET_NAME=aws_secret_access_key_${CIRCLE_BRANCH}
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_SECRET_NAME}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_SECRET_NAME}
            docker run --rm -w="/code" -e TF_VAR_app_name -e TF_VAR_region -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e CIRCLE_BRANCH -v "${HOME}"/project/:/code/ unfor19/terraform-alpine:$TERRAFORM_VERSION /code/scripts/terraform-apply.sh
